name:                mp5-scheme
version:             0.2.0.0
synopsis:            Write A Lisp Interpreter
license:             NCSA

description:         Please see the README

dependencies:
- base >= 4.7 && < 5
- unordered-containers
- parsec

library:
  source-dirs: app

executables:
  mp5-scheme:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mp5-scheme

tests:
  test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mp5-scheme